// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCA_FA2.Data;

#nullable disable

namespace NCA_FA2.Migrations
{
    [DbContext(typeof(FeedbackDBContext))]
    partial class FeedbackDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NCA_FA2.Models.FeedbackViewModel", b =>
                {
                    b.Property<string>("Complaint_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Complaint_Id")
                        .HasColumnType("int");

                    b.Property<string>("Complaint_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compliment_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Compliment_Id")
                        .HasColumnType("int");

                    b.Property<string>("Compliment_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compliment_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compliment_Text")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("FeedbackViewModel");
                });

            modelBuilder.Entity("classactivityforms_1.Models.ComplaintModel", b =>
                {
                    b.Property<int>("Complaint_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Complaint_Id"));

                    b.Property<string>("Complaint_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Complaint_Id");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("classactivityforms_1.Models.ComplimentModel", b =>
                {
                    b.Property<int>("Compliment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Compliment_Id"));

                    b.Property<string>("Compliment_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compliment_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compliment_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compliment_Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Compliment_Id");

                    b.ToTable("Compliments");
                });
#pragma warning restore 612, 618
        }
    }
}
